name: Postgres MCP

on:
  push:
    tags:
      - 'v*'

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.3'
      - run: go version

      - name: Install dependencies
        run: |
          go mod download

      - name: Build applications
        run: |
          GOOS=windows GOARCH=amd64 go build -o pg-mcp.exe cmd/pg-mcp/main.go
          GOOS=linux GOARCH=amd64 go build -o pg-mcp cmd/pg-mcp/main.go

      - name: Package applications
        run: |
          mkdir windows-pg-mcp && cp pg-mcp.exe README.md windows-pg-mcp/
          mkdir linux-pg-mcp && cp pg-mcp README.md linux-pg-mcp/
          tar -czf windows-pg-mcp.tar.gz windows-pg-mcp
          tar -czf linux-pg-mcp.tar.gz linux-pg-mcp
          sha256sum *.tar.gz > checksums-pg-mcp.txt

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            windows-pg-mcp.tar.gz \
            linux-pg-mcp.tar.gz \
            checksums-pg-mcp.txt \
            --title "PostgreSQL MCP Server ${{ github.ref_name }}" \
            --generate-notes
